### ISSUE TITLE
Tensor Index Issue with HF generate's num_return_sequences > 1

### ISSUE THREAD

**Issue by dhuvik** [ZurichNLP/mbr#9]
Currently running into an issue that arises whenever the num_return_sequences > 1. Otherwise the code works when num_return_sequences=1: 

```
mbr_bart = MBR(BartForConditionalGeneration).from_pretrained("mymodel")
mbr_config = MBRConfig(
            num_samples=5,
        )

inps = bart_tokenizer(src, return_tensors='pt').to('cuda')
mbr_bart.generate(**inps, do_sample=True, mbr_config=mbr_config, tokenizer=bart_tokenizer, num_beams=1, num_return_sequences=2, max_new_tokens=25, epsilon_cutoff=0.02)

-----------------------------------------------------------------------------------------------------------------------

IndexError                                Traceback (most recent call last)
Cell In[66], line 24
     18 mbr_config = MBRConfig(
     19             num_samples=5,
     20         )
     23 inps = bart_tokenizer(src, return_tensors='pt').to('cuda')
---> 24 mbr_bart.generate(**inps, do_sample=True, mbr_config=mbr_config, tokenizer=bart_tokenizer, num_beams=1, num_return_sequences=2, max_new_tokens=25, epsilon_cutoff=0.02)

File ~/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File ~/.local/lib/python3.9/site-packages/mbr/generation/utils.py:506, in MBRGenerationMixin.generate(self, inputs, generation_config, references_config, mbr_config, tokenizer, metric_runner, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, assistant_model, streamer, negative_prompt_ids, negative_prompt_attention_mask, progress_bar, **kwargs)
    498 output = MBROutput(
    499     sequences=generation_config.pad_token_id * torch.ones((batch_size, max_length), dtype=torch.long),
    500     all_samples=(tuple(samples) if mbr_config.output_all_samples else None),
   (...)
    503     metric_scores=(metric_output if mbr_config.output_metric_scores else None),
    504 )
    505 for batch_idx, sample_idx in enumerate(top_metric_indices):
--> 506     output.sequences[batch_idx][:sample_ids[sample_idx].shape[1]] = sample_ids[sample_idx][batch_idx]
    508 if mbr_config.return_dict_in_generate:
    509     return output

IndexError: index 1 is out of bounds for dimension 0 with size 1
```

Thank you for your time!

**Comment by jvamvas** [comment]
@dhuvik Thanks for reporting this.

I think num_return_sequences > 1 only makes sense with sampling, where you can sample several i.i.d. generations. It does not make sense with MBR decoding.

I have now added an assertion in the code to make sure that num_return_sequences == 1.

**Comment by dhuvik** [comment]
Thank you @jvamvas!

I had only done a surface level read of the paper and came across the MBR with sampling portion and assumed there was a method to get multiple sequences back from the different hypotheses. Am I correct in my understanding that any (ancestral, top-p, or beam) sampling method can be used to generate the reduced hypotheses list upon which MBR decoding is used as the decision process? 

I tried generating the samples within a loop and got some (not a lot) variability between generations. Based on this it didn't seem like MBR and greedy decoding was the right comparison and MBR vs beam search seemed off as well since beam search could have been used to generate the hypotheses. Having thought deeply on this, do you have a suggestion as to how to better guage the accuracy and diversity of generations from MBR decoding or should it be treated more of a greedy decoding approach with BEER/BLEU to be used fro the resulting samples?

Many thanks for your input,
Dhuvi

**Comment by jvamvas** [comment]
> Am I correct in my understanding that any (ancestral, top-p, or beam) sampling method can be used to generate the reduced hypotheses list upon which MBR decoding is used as the decision process?

Yes, but right now this library only supports sampling, like ancestral, top-p etc. Beam search works theoretically but is not implemented.

> I tried generating the samples within a loop and got some (not a lot) variability between generations.

If your goal is to create a diverse set of hypotheses, then I am not sure MBR is the right approach. However, there has been recent paper on this that could offer a different perspective: https://arxiv.org/abs/2401.05054
